{% set name = "st-annotated-text" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b0134dcf734697cc3dbdb11862c4174071e7fb6f365af55a37c710d357fd88a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - htbuilder
    - streamlit
    - python >={{ python_min }}

test:
  imports:
    - annotated_text
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tvst/st-annotated-text
  summary: A simple component to display annotated text in Streamlit apps.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
