{% set name = "st-annotated-text" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/st-annotated-text-{{ version }}.tar.gz
  sha256: a8ccb9a35c078ef22c6ebb244a9a0605ce27f1fd699f55939497669081b79630

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - htbuilder
    - streamlit
    - python >={{ python_min }}

test:
  imports:
    - annotated_text
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tvst/st-annotated-text
  summary: A simple component to display annotated text in Streamlit apps.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
