{% set name = "st-annotated-text" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/st-annotated-text-{{ version }}.tar.gz
  sha256: 8337fcb3271c7f59a877e0fce5d822613116a4036d06890fc68cf840430b40aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - htbuilder
    - streamlit
    - python >=3.5

test:
  imports:
    - annotated_text
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tvst/st-annotated-text
  summary: A simple component to display annotated text in Streamlit apps.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
